import { SubscriptionPlan } from '../types';

export const DEFAULT_PLANS: SubscriptionPlan[] = [
  // FREE COMMUNITY TIER
  {
    id: 'free',
    name: 'Free Community',
    tier: 'FREE',
    aiMode: 'MANAGED',
    monthlyPriceINR: 0,
    yearlyPriceINR: 0,
    description: 'Explore verified market intelligence and test research pipelines for early experiments.',
    badge: 'Free Forever',
    features: [
      '2 Deep Market Research Runs / month',
      '5 Competitor Crawl Pages / month',
      '50,000 Managed AI Tokens / month',
      'Basic Evidence Collection & Fact Extraction',
      'Bring Your Own Key (BYOK) Allowed',
      'Community Support',
    ],
    quotas: {
      monthlyResearchRuns: 2,
      monthlyCompetitorCrawls: 5,
      monthlyAITokens: 50000,
      maxConcurrentJobs: 1,
      maxCompetitorUniverse: 3,
      warRoomAccess: false,
      exportReports: false,
      byokAllowed: true,
      priorityRouting: false,
      customIntegrations: false,
    },
  },

  // STARTER MANAGED
  {
    id: 'starter_managed',
    name: 'Starter (Managed AI)',
    tier: 'STARTER',
    aiMode: 'MANAGED',
    monthlyPriceINR: 999,
    yearlyPriceINR: 9990, // Save 2 months
    description: 'All-inclusive platform with zero API keys to configure. Ideal for solo founders and early PMs.',
    badge: 'Zero Setup',
    features: [
      '10 Deep Market Research Runs / month',
      '25 Competitor Crawl Pages / month',
      '500,000 Managed AI Tokens / month',
      'Cross-Source Conflict Detection',
      'Market War Room & Strategic Matrix',
      'Export PDF & Markdown Briefs',
      'Standard Multi-Model AI Routing',
      'Email Support (48h response)',
    ],
    quotas: {
      monthlyResearchRuns: 10,
      monthlyCompetitorCrawls: 25,
      monthlyAITokens: 500000,
      maxConcurrentJobs: 2,
      maxCompetitorUniverse: 10,
      warRoomAccess: true,
      exportReports: true,
      byokAllowed: false,
      priorityRouting: false,
      customIntegrations: false,
    },
  },

  // STARTER BYOK
  {
    id: 'starter_byok',
    name: 'Starter (BYOK)',
    tier: 'STARTER',
    aiMode: 'BYOK',
    monthlyPriceINR: 399,
    yearlyPriceINR: 3990,
    description: 'Discounted rate when you bring your own OpenAI, Anthropic, or Gemini API keys.',
    badge: '60% BYOK Discount',
    features: [
      '10 Deep Market Research Runs / month',
      '25 Competitor Crawl Pages / month',
      'Bring Your Own Key (OpenAI, Anthropic, Gemini, OpenRouter)',
      'Direct provider token billing (No markup)',
      'Cross-Source Conflict Detection',
      'Market War Room & Strategic Matrix',
      'Export PDF & Markdown Briefs',
      'AES-256 Encrypted Key Vault',
    ],
    quotas: {
      monthlyResearchRuns: 10,
      monthlyCompetitorCrawls: 25,
      monthlyAITokens: 0, // Direct provider
      maxConcurrentJobs: 2,
      maxCompetitorUniverse: 10,
      warRoomAccess: true,
      exportReports: true,
      byokAllowed: true,
      priorityRouting: false,
      customIntegrations: false,
    },
  },

  // PRO MANAGED (POPULAR)
  {
    id: 'pro_managed',
    name: 'Pro (Managed AI)',
    tier: 'PRO',
    aiMode: 'MANAGED',
    monthlyPriceINR: 2999,
    yearlyPriceINR: 29990,
    highlighted: true,
    badge: 'Most Popular',
    description: 'Full competitive command center for fast-moving product marketing and strategy teams.',
    features: [
      '50 Deep Market Research Runs / month',
      '100 Competitor Crawl Pages / month',
      '2,500,000 Managed AI Tokens / month',
      'Unlimited Market War Room Simulations',
      'Competitor Move Monitor & Shift Tracking',
      'Custom Positioning & Campaign Briefs',
      'Priority AI Routing & Automatic Fallback',
      'Kanban Action Task Integration',
      'Priority Support (12h response)',
    ],
    quotas: {
      monthlyResearchRuns: 50,
      monthlyCompetitorCrawls: 100,
      monthlyAITokens: 2500000,
      maxConcurrentJobs: 5,
      maxCompetitorUniverse: 25,
      warRoomAccess: true,
      exportReports: true,
      byokAllowed: false,
      priorityRouting: true,
      customIntegrations: false,
    },
  },

  // PRO BYOK
  {
    id: 'pro_byok',
    name: 'Pro (BYOK)',
    tier: 'PRO',
    aiMode: 'BYOK',
    monthlyPriceINR: 1199,
    yearlyPriceINR: 11990,
    highlighted: true,
    badge: 'Pro BYOK Value',
    description: 'Pro command center powered by your enterprise API keys with massive cost savings.',
    features: [
      '50 Deep Market Research Runs / month',
      '100 Competitor Crawl Pages / month',
      'Bring Your Own Key (OpenAI, Claude 3.7 Sonnet, Gemini 2.0 Pro)',
      'Direct provider token billing (Zero markup)',
      'Unlimited Market War Room Simulations',
      'Competitor Move Monitor & Shift Tracking',
      'Custom Positioning & Campaign Briefs',
      'Switch between models anytime in Settings',
      'Priority Support (12h response)',
    ],
    quotas: {
      monthlyResearchRuns: 50,
      monthlyCompetitorCrawls: 100,
      monthlyAITokens: 0,
      maxConcurrentJobs: 5,
      maxCompetitorUniverse: 25,
      warRoomAccess: true,
      exportReports: true,
      byokAllowed: true,
      priorityRouting: true,
      customIntegrations: false,
    },
  },

  // BUSINESS MANAGED
  {
    id: 'business_managed',
    name: 'Business (Managed AI)',
    tier: 'BUSINESS',
    aiMode: 'MANAGED',
    monthlyPriceINR: 7999,
    yearlyPriceINR: 79990,
    badge: 'Enterprise Grade',
    description: 'Scale market intelligence across multiple business units and high-frequency monitoring.',
    features: [
      '500 Deep Market Research Runs / month',
      '500 Competitor Crawl Pages / month',
      '10,000,000 Managed AI Tokens / month',
      'Highest Priority AI Compute Allocation',
      'Advanced Custom Evaluation Benchmark Runs',
      'Deep Company Footprint Discovery Engine',
      'Dedicated Slack/Teams Channel Support',
      'Custom SLA & 99.9% Uptime Guarantee',
    ],
    quotas: {
      monthlyResearchRuns: 500,
      monthlyCompetitorCrawls: 500,
      monthlyAITokens: 10000000,
      maxConcurrentJobs: 10,
      maxCompetitorUniverse: 100,
      warRoomAccess: true,
      exportReports: true,
      byokAllowed: false,
      priorityRouting: true,
      customIntegrations: true,
    },
  },

  // BUSINESS BYOK
  {
    id: 'business_byok',
    name: 'Business (BYOK)',
    tier: 'BUSINESS',
    aiMode: 'BYOK',
    monthlyPriceINR: 3499,
    yearlyPriceINR: 34990,
    badge: 'Scale BYOK',
    description: 'High-volume research infrastructure backed by your custom corporate model agreements.',
    features: [
      '500 Deep Market Research Runs / month',
      '500 Competitor Crawl Pages / month',
      'Unlimited AI Token Usage (Billed via your provider contracts)',
      'All Providers Supported (OpenAI, Anthropic, Gemini, OpenRouter)',
      'Dedicated Multi-Provider Gateway Failover',
      'Full Digital Footprint Crawler Budget',
      'Dedicated Strategy Review Sessions',
      'Custom SLA & Support',
    ],
    quotas: {
      monthlyResearchRuns: 500,
      monthlyCompetitorCrawls: 500,
      monthlyAITokens: 0,
      maxConcurrentJobs: 10,
      maxCompetitorUniverse: 100,
      warRoomAccess: true,
      exportReports: true,
      byokAllowed: true,
      priorityRouting: true,
      customIntegrations: true,
    },
  },
];

export function getPlanById(planId: string): SubscriptionPlan | undefined {
  return DEFAULT_PLANS.find((p) => p.id === planId);
}
