import React, { useState, useEffect } from 'react';
import { api } from '../../lib/api';
import {
  ResearchJob,
  ResearchShareLink,
  IntelligenceReport,
  CampaignBrief,
  Evidence,
  ResearchSource,
  ConflictItem,
  ResearchReviewAssignment,
} from '../../types';
import {
  ExternalLink,
  Lock,
  Eye,
  CheckCircle2,
  AlertTriangle,
  FileText,
  Copy,
  Layers,
  Users,
  Building2,
  Target,
  Sparkles,
  ShieldCheck,
  Send,
  X,
  RefreshCw,
  MessageSquare,
} from 'lucide-react';
import { useWorkspace } from '../../context/WorkspaceContext';

interface SharedResearchPreviewModalProps {
  token: string | null;
  onClose: () => void;
}

export const SharedResearchPreviewModal: React.FC<SharedResearchPreviewModalProps> = ({
  token,
  onClose,
}) => {
  const { addToast } = useWorkspace();

  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [data, setData] = useState<{
    shareLink: ResearchShareLink;
    job: ResearchJob;
    intelligence?: IntelligenceReport;
    campaignBrief?: CampaignBrief;
    evidence: Evidence[];
    sources?: ResearchSource[];
    conflicts?: ConflictItem[];
    reviews?: ResearchReviewAssignment[];
  } | null>(null);

  const [reviewerComment, setReviewerComment] = useState<string>('');
  const [submittingComment, setSubmittingComment] = useState<boolean>(false);
  const [submittedFeedback, setSubmittedFeedback] = useState<string | null>(null);

  useEffect(() => {
    if (!token) return;

    const fetchSharedData = async () => {
      try {
        setLoading(true);
        setError(null);
        const result = await api.getSharedResearch(token);
        setData(result);
      } catch (err: any) {
        setError(err.message || 'Failed to load shared research link.');
      } finally {
        setLoading(false);
      }
    };

    fetchSharedData();
  }, [token]);

  if (!token) return null;

  const handleApproveResearch = async () => {
    if (!data?.reviews || data.reviews.length === 0) {
      addToast('Feedback noted: Research verified and marked approved', 'success');
      setSubmittedFeedback('Approved by reviewer');
      return;
    }

    try {
      setSubmittingComment(true);
      const activeReview = data.reviews[0];
      await api.updateReview(activeReview.id, {
        status: 'APPROVED',
        reviewerFeedback: reviewerComment || 'All competitive claims and pricing verified.',
      });
      setSubmittedFeedback('Review status submitted: APPROVED');
      addToast('Approval recorded successfully', 'success');
    } catch (err: any) {
      addToast(err.message, 'error');
    } finally {
      setSubmittingComment(false);
    }
  };

  const handleRequestChanges = async () => {
    if (!reviewerComment.trim()) {
      addToast('Please provide feedback notes explaining the requested adjustments', 'warning');
      return;
    }

    try {
      setSubmittingComment(true);
      if (data?.reviews && data.reviews.length > 0) {
        const activeReview = data.reviews[0];
        await api.updateReview(activeReview.id, {
          status: 'CHANGES_REQUESTED',
          reviewerFeedback: reviewerComment.trim(),
        });
      }
      setSubmittedFeedback(`Changes Requested: "${reviewerComment.trim()}"`);
      addToast('Changes requested sent to team', 'info');
      setReviewerComment('');
    } catch (err: any) {
      addToast(err.message, 'error');
    } finally {
      setSubmittingComment(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-zinc-900/70 backdrop-blur-xs overflow-y-auto animate-in fade-in">
      <div
        className="bg-white w-full max-w-4xl rounded-2xl border border-zinc-200 shadow-2xl overflow-hidden my-auto flex flex-col max-h-[92vh]"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="p-5 border-b border-zinc-200 flex items-center justify-between bg-zinc-50/80">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-600 text-white flex items-center justify-center shadow-xs">
              <Eye className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-base font-bold text-zinc-900">
                  {data?.job.businessName || 'Shared Research Dossier'}
                </h2>
                <span className="text-[10px] font-bold px-2 py-0.5 bg-emerald-50 text-emerald-700 border border-emerald-200 rounded">
                  Live Shared Dossier
                </span>
              </div>
              <p className="text-xs text-zinc-500 mt-0.5">
                Public read access • Generated by {data?.shareLink.createdByName || 'Alex Chen'}
              </p>
            </div>
          </div>

          <button
            id="btn-close-shared-preview"
            onClick={onClose}
            className="p-1.5 text-zinc-400 hover:text-zinc-700 hover:bg-zinc-100 rounded-lg transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body Content */}
        <div className="p-6 overflow-y-auto space-y-6 flex-1 text-xs">
          {loading && (
            <div className="py-16 text-center space-y-3">
              <RefreshCw className="w-6 h-6 animate-spin text-indigo-600 mx-auto" />
              <div className="text-xs text-zinc-500 font-medium">
                Loading encrypted research snapshot...
              </div>
            </div>
          )}

          {error && (
            <div className="p-6 bg-rose-50 border border-rose-200 rounded-xl text-center space-y-2">
              <AlertTriangle className="w-8 h-8 text-rose-600 mx-auto" />
              <div className="font-bold text-rose-900 text-sm">Access Restricted</div>
              <p className="text-xs text-rose-700 max-w-md mx-auto">{error}</p>
            </div>
          )}

          {data && !loading && (
            <div className="space-y-6">
              {/* Header Overview Card */}
              <div className="bg-zinc-50 border border-zinc-200 rounded-xl p-4 space-y-3">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <span className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">
                      Campaign Objective
                    </span>
                    <p className="font-semibold text-zinc-900 text-xs mt-0.5">
                      {data.job.campaignObjective}
                    </p>
                  </div>
                  <div>
                    <span className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">
                      Target Audience
                    </span>
                    <p className="font-semibold text-zinc-900 text-xs mt-0.5">
                      {data.job.targetAudience}
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-4 pt-2 border-t border-zinc-200/60 text-[11px] text-zinc-500 flex-wrap">
                  <span>
                    Scope:{' '}
                    <strong className="text-zinc-800">
                      {data.shareLink.scope.replace('_', ' ')}
                    </strong>
                  </span>
                  <span>•</span>
                  <span>
                    Evidence Claims:{' '}
                    <strong className="text-zinc-800">{data.evidence.length}</strong>
                  </span>
                  <span>•</span>
                  <span>
                    Permission:{' '}
                    <strong className="text-zinc-800">
                      {data.shareLink.permission.replace('_', ' ')}
                    </strong>
                  </span>
                </div>
              </div>

              {/* Strategic Insights & Findings (if included) */}
              {data.intelligence && (
                <div className="space-y-3">
                  <h3 className="font-bold text-zinc-900 flex items-center gap-1.5 text-xs">
                    <Sparkles className="w-4 h-4 text-indigo-600" />
                    <span>Key Market Findings & Directives</span>
                  </h3>
                  <div className="bg-white border border-zinc-200 rounded-xl p-4 space-y-3 shadow-2xs">
                    <div>
                      <span className="font-bold text-zinc-800">Executive Synthesis:</span>
                      <p className="text-zinc-600 mt-1 leading-relaxed">
                        {data.intelligence.executiveSummary}
                      </p>
                    </div>

                    {data.intelligence.marketGaps && data.intelligence.marketGaps.length > 0 && (
                      <div className="pt-2 border-t border-zinc-100">
                        <span className="font-bold text-zinc-800">High-Impact Market Gaps:</span>
                        <ul className="list-disc pl-5 mt-1 space-y-1 text-zinc-600">
                          {data.intelligence.marketGaps.map((gap, i) => (
                            <li key={i}>{gap}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* Evidence Claims & Pricing Matrix */}
              <div className="space-y-3">
                <h3 className="font-bold text-zinc-900 flex items-center gap-1.5 text-xs">
                  <ShieldCheck className="w-4 h-4 text-emerald-600" />
                  <span>Verified Competitor Evidence Claims ({data.evidence.length})</span>
                </h3>

                <div className="grid grid-cols-1 gap-2.5">
                  {data.evidence.map((ev) => (
                    <div
                      key={ev.id}
                      className="bg-white border border-zinc-200 rounded-xl p-3 space-y-2 hover:border-zinc-300 transition-colors"
                    >
                      <div className="flex items-center justify-between">
                        <span className="font-bold text-zinc-900">{ev.claim}</span>
                        <span className="text-[10px] font-mono px-2 py-0.5 bg-zinc-100 text-zinc-700 rounded font-semibold">
                          {ev.evidenceType}
                        </span>
                      </div>
                      <p className="text-[11px] text-zinc-600 italic bg-zinc-50 p-2 rounded-lg border border-zinc-100 font-mono">
                        "{ev.extractedQuote}"
                      </p>
                      <div className="flex items-center justify-between text-[10px] text-zinc-400">
                        <span>Confidence: {ev.confidenceScore}%</span>
                        <span className="truncate max-w-xs">{ev.sourceUrl}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Reviewer Feedback Section (Interactive if permission allows) */}
              {(data.shareLink.permission === 'CAN_COMMENT' ||
                data.shareLink.permission === 'REVIEW_APPROVAL') && (
                <div className="bg-indigo-50/70 border border-indigo-200 rounded-xl p-4 space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-indigo-950 flex items-center gap-1.5">
                      <MessageSquare className="w-4 h-4 text-indigo-600" />
                      <span>Reviewer Feedback & Sign-Off</span>
                    </span>
                    <span className="text-[10px] font-bold px-2 py-0.5 bg-indigo-100 text-indigo-800 rounded">
                      Interactive Reviewer Mode
                    </span>
                  </div>

                  {submittedFeedback ? (
                    <div className="p-3 bg-emerald-100 text-emerald-900 rounded-lg font-semibold text-xs flex items-center gap-2">
                      <CheckCircle2 className="w-4 h-4 text-emerald-700" />
                      <span>{submittedFeedback}</span>
                    </div>
                  ) : (
                    <div className="space-y-2.5">
                      <textarea
                        rows={2}
                        placeholder="Add review notes, comments, or competitor validation comments..."
                        value={reviewerComment}
                        onChange={(e) => setReviewerComment(e.target.value)}
                        className="w-full bg-white border border-indigo-200 rounded-lg p-2.5 text-xs text-zinc-800 outline-none focus:ring-2 focus:ring-indigo-500 resize-none"
                      />

                      <div className="flex items-center justify-end gap-2">
                        <button
                          onClick={handleRequestChanges}
                          disabled={submittingComment}
                          className="px-3 py-1.5 bg-white hover:bg-zinc-100 text-amber-800 font-bold border border-amber-300 rounded-lg text-xs transition-colors"
                        >
                          Request Changes
                        </button>

                        <button
                          onClick={handleApproveResearch}
                          disabled={submittingComment}
                          className="px-4 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white font-bold rounded-lg text-xs transition-colors flex items-center gap-1.5"
                        >
                          <CheckCircle2 className="w-3.5 h-3.5" />
                          <span>Approve & Verify Findings</span>
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
